# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.70.0"
    }
  }
}

provider "aws" {
  region = "eu-west-3"
  allowed_account_ids = ["123456789013"]
  assume_role {
    role_arn     = "arn:aws:iam::123456789013:role/terraform-admin"
  }
}
